#### TEXTOBJ ####

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
## バッファ全体
# aE, iE （デフォルト(ae,ie)がvimtexと干渉するので変更）
repo = 'kana/vim-textobj-entire'
lazy = 1
on_map = {x='<Plug>', o='<Plug>'}
hook_add = '''
let g:textobj_entire_no_default_key_mappings=1
omap aE <Plug>(textobj-entire-a)
omap iE <Plug>(textobj-entire-i)
xmap aE <Plug>(textobj-entire-a)
xmap iE <Plug>(textobj-entire-i)
'''

[[plugins]]
## カーソル行
# al, il
repo = 'kana/vim-textobj-line'
lazy = 1
on_map = {x=['al', 'il'], o=['al', 'il']}

[[plugins]]
## 連続したスペース
# aS, iS
repo = 'saihoooooooo/vim-textobj-space'
lazy = 1
on_map = {x=['aS', 'iS'], o=['aS', 'iS']}

[[plugins]]
## function for C, java, vim
# af, if
repo = 'kana/vim-textobj-function'
lazy = 1
on_ft = ['c', 'java', 'vim']

[[plugins]]
## 関数の引数
# a,  i,
repo = 'sgur/vim-textobj-parameter'
lazy = 1
on_map = {x=['a,', 'i,'], o=['a,', 'i,']}

[[plugins]]
## コメント
# ac, ic, aC, iC
repo = 'glts/vim-textobj-comment'
lazy = 1
[plugins.on_map]
x=['ac', 'ic', 'aC', 'iC']
o=['ac', 'ic', 'aC', 'iC']

[[plugins]]
## word in word: snake_case, camelCase, PascalCase, kebab-case
# am, im
repo = 'rhysd/vim-textobj-wiw'
lazy = 1
on_map = {x=['am', 'im'], o=['am', 'im']}

[[plugins]]
## toml file for dein.vim
# iP, aP, ir, ah
repo = 'KosukeMizuno/vim-textobj-dein'
lazy = 1
on_ft = 'toml'

[[plugins]]
## number
# an: dicimal number in various notation, e.g., 11, 3.14, -5, +6.02e23
# in: dicimal digits in integer
repo = 'tkhren/vim-textobj-numeral'
lazy = 1
on_map = {x='<Plug>', o='<Plug>'}
hook_add = '''
let g:textobj_numeral_no_default_key_mappings = 1
xmap an <Plug>(textobj-numeral-a)
omap an <Plug>(textobj-numeral-a)
xmap in <Plug>(textobj-numeral-i)
omap in <Plug>(textobj-numeral-i)
'''

[[plugins]]
repo = 'mattn/vim-textobj-url'
lazy = 1
on_map = {x=['au', 'iu'], o=['au', 'iu']}


#### OPERATOR ####

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
## レジスタを汚さずに文字列置換
# r にマップしている
repo = 'kana/vim-operator-replace'
lazy = 1
on_map = {n='<Plug>', x='<Plug>'}

[[plugins]]
## 末尾のホワイトスペースを除去
# g= にマップしている
repo = 'rhysd/vim-operator-trailingspace-killer'
lazy = 1
on_map = {n='<Plug>', x='<Plug>'}

[[plugins]]
repo = 'machakann/vim-sandwich'
lazy = 1
[plugins.on_map]
n=['sa', 'sd', 'sr', 'sdb', 'srb']
x=['sa', 'sd', 'sr', 'ib', 'ab', 'is', 'as']
o=['sa', 'ib', 'ab', 'is', 'as']
